//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DutiesFamily.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Family
    {
        public Family()
        {
            this.Duty = new HashSet<Duty>();
            this.User = new HashSet<User>();
        }
    
        public long IdFamily { get; set; }
        public string FamilyName { get; set; }
        public string Password { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<Duty> Duty { get; set; }
        public virtual ICollection<User> User { get; set; }
    }
}
